In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from statannotations.Annotator import Annotator
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import multipletests
from skbio.stats.composition import ancom
from skbio.stats.composition import ancombc
from skbio.stats.composition import struc_zero

In [ ]:
asv = 'data/2_preprocessed/prv10/prv10_ft.tsv'
mmi = 'data/mmi.tsv'
sha = 'data/2_preprocessed/diversity/shannon.tsv'

otu_df = pd.read_csv(asv, sep='\t', index_col=0)
meta_df = pd.read_csv(mmi, sep='\t').set_index('#SampleID')
shannon_df = pd.read_csv(sha, sep='\t', index_col=0)


otu_df

,d__Bacteria;__;__;__;__;__,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales_737866;f__Enterobacteriaceae_A_725029;g__Escherichia,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595427;g__Sutterella,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger_A_73129,d__Archaea;p__Methanobacteriota_A_1229;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanobrevibacter_A,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_H_857956,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Chitinophagales;f__Chitinophagaceae;g__Hydrotalea,d__Bacteria;p__Actinomycetota;c__Actinomycetes;o__Actinomycetales;f__Bifidobacteriaceae;g__Bifidobacterium_388775,d__Bacteria;p__Bacillota_I;c__Bacilli_A;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus_B,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A_141780,...,d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Eggerthellaceae;g__Gordonibacter,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595427;g__Parasutterella_564865,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595421;g__Oxalobacter,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__UMGS1071,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__Hydrogeniiclostridium,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Negativibacillus,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__QAKW01;g__,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__Clostridium_A_51961,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Ruminiclostridium_E
SRR23478191,0.0,120.0,0.0,0.0,0.0,189.0,0.0,23.0,317.0,6.0,...,0.0,328.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0
SRR23478195,1.0,132.0,0.0,1.0,1.0,2.0,0.0,154.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SRR23478196,2.0,328.0,0.0,0.0,0.0,2.0,0.0,799.0,1.0,42.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SRR23478197,0.0,38.0,0.0,1.0,0.0,374.0,0.0,1246.0,1.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
SRR23478198,0.0,19.0,0.0,0.0,0.0,9.0,0.0,259.0,0.0,36.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR29856096,0.0,6.0,0.0,158.0,0.0,341.0,0.0,3.0,0.0,0.0,...,0.0,1.0,10.0,8.0,0.0,7.0,0.0,5.0,0.0,1.0
SRR29856097,0.0,118.0,0.0,123.0,0.0,348.0,1.0,72.0,0.0,9.0,...,0.0,0.0,0.0,5.0,2.0,14.0,0.0,4.0,0.0,0.0
SRR29856098,0.0,42.0,0.0,2.0,0.0,42.0,0.0,173.0,3.0,3.0,...,3.0,47.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
SRR29856099,0.0,49.0,0.0,0.0,0.0,936.0,6.0,223.0,10.0,0.0,...,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0
SRR29856102,0.0,17.0,1.0,218.0,0.0,48.0,32.0,83.0,456.0,3.0,...,4.0,62.0,0.0,14.0,0.0,3.0,0.0,0.0,1.0,0.0

In [5]:
otu_rel = otu_df.div(otu_df.sum(axis=1), axis = 0)

otu_rel

,d__Bacteria;__;__;__;__;__,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales_737866;f__Enterobacteriaceae_A_725029;g__Escherichia,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595427;g__Sutterella,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Gemmiger_A_73129,d__Archaea;p__Methanobacteriota_A_1229;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__Methanobrevibacter_A,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides_H_857956,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Chitinophagales;f__Chitinophagaceae;g__Hydrotalea,d__Bacteria;p__Actinomycetota;c__Actinomycetes;o__Actinomycetales;f__Bifidobacteriaceae;g__Bifidobacterium_388775,d__Bacteria;p__Bacillota_I;c__Bacilli_A;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus_B,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Lachnospirales;f__Lachnospiraceae;g__Blautia_A_141780,...,d__Bacteria;p__Actinomycetota;c__Coriobacteriia;o__Coriobacteriales;f__Eggerthellaceae;g__Gordonibacter,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595427;g__Parasutterella_564865,d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Burkholderiales;f__Burkholderiaceae_A_595421;g__Oxalobacter,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__UMGS1071,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__Hydrogeniiclostridium,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Negativibacillus,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__QAKW01;g__,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Acutalibacteraceae;g__Clostridium_A_51961,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Monoglobales;f__Monoglobaceae;g__Monoglobus,d__Bacteria;p__Bacillota_A_368345;c__Clostridia_258483;o__Oscillospirales;f__Ruminococcaceae;g__Ruminiclostridium_E
SRR23478191,0.000000,0.019215,0.000000,0.000000,0.000000,0.030264,0.000000,0.003683,0.050761,0.000961,...,0.000000,0.052522,0.00000,0.001922,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
SRR23478195,0.000159,0.021046,0.000000,0.000159,0.000159,0.000319,0.000000,0.024554,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
SRR23478196,0.000334,0.054767,0.000000,0.000000,0.000000,0.000334,0.000000,0.133411,0.000167,0.007013,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
SRR23478197,0.000000,0.006278,0.000000,0.000165,0.000000,0.061788,0.000000,0.205848,0.000165,0.000000,...,0.000000,0.000000,0.00000,0.000826,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
SRR23478198,0.000000,0.003029,0.000000,0.000000,0.000000,0.001435,0.000000,0.041295,0.000000,0.005740,...,0.000000,0.000000,0.00000,0.001594,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR29856096,0.000000,0.000972,0.000000,0.025604,0.000000,0.055258,0.000000,0.000486,0.000000,0.000000,...,0.000000,0.000162,0.00162,0.001296,0.000000,0.001134,0.0,0.000810,0.000000,0.000162
SRR29856097,0.000000,0.018938,0.000000,0.019740,0.000000,0.055850,0.000160,0.011555,0.000000,0.001444,...,0.000000,0.000000,0.00000,0.000802,0.000321,0.002247,0.0,0.000642,0.000000,0.000000
SRR29856098,0.000000,0.007015,0.000000,0.000334,0.000000,0.007015,0.000000,0.028896,0.000501,0.000501,...,0.000501,0.007850,0.00000,0.003007,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
SRR29856099,0.000000,0.007809,0.000000,0.000000,0.000000,0.149163,0.000956,0.035538,0.001594,0.000000,...,0.000000,0.000000,0.00000,0.000797,0.000319,0.000000,0.0,0.000000,0.000000,0.000000
SRR29856102,0.000000,0.002770,0.000163,0.035522,0.000000,0.007821,0.005214,0.013525,0.074303,0.000489,...,0.000652,0.010103,0.00000,0.002281,0.000000,0.000489,0.0,0.000000,0.000163,0.000000

In [6]:
otu_rel_T = otu_rel.T

In [7]:
otu_rel_T
print(otu_rel_T['SRR23478198'].sum())
print(otu_rel_T['SRR29856102'].sum())

1.0
1.0

In [ ]:
otu_rel_T.to_csv("data/2_preprocessed/ab_rel.csv")