In [6]:
import pandas as pd
import numpy as np

In [7]:
h_nodes = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/high/high_nodes_topology.csv", sep=',')
h_edges = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/high/high_edges.csv", sep=',')
h_re_ab = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/high/high_rel_abundance.csv", sep=',')
l_nodes = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/low/low_nodes_topology.csv", sep=',')
l_edges = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/low/low_edges.csv", sep=',')
l_re_ab = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/low/low_rel_abundance.csv", sep=',')
p_nodes = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/pibd/pibd_nodes_topology.csv", sep=',')
p_edges = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/pibd/pibd_edges.csv", sep=',')
p_re_ab = pd.read_csv("data/3_results/5_network_analysis/5_2_network_export/pibd/pibd_rel_abundance.csv", sep=',')

In [8]:
roman_map = {
    1.0: "I",
    2.0: "II",
    3.0: "III",
    4.0: "IV",
    5.0: "V",
    6.0: "VI",
    7.0: "VII",
    8.0: "VIII",
    9.0: "IX",
    10.0: "X",
    11.0: "XI"
}


h_nodes["cluster"] = h_nodes["cluster"].replace(roman_map)
l_nodes["cluster"] = l_nodes["cluster"].replace(roman_map)
p_nodes["cluster"] = p_nodes["cluster"].replace(roman_map)

In [9]:
h_nodes

,Label,Id,cluster,degree,betweenness,closeness,eigenvector,abundance,phylum
0,Sutterella,1,I,0.010638,0.000000,0.526809,0.105146,70,Pseudomonadota
1,Gemmiger_A_73129,2,II,0.037234,0.167105,0.620746,0.000616,16191,Bacillota_A_368345
2,Methanobrevibacter_A,3,III,0.015957,0.001316,0.456678,0.019196,2785,Methanobacteriota_A_1229
3,Bacteroides_H_857956,4,I,0.122340,0.096491,0.872304,0.912477,30354,Bacteroidota
4,Bifidobacterium_388775,5,II,0.095745,0.021272,0.756596,0.000724,20069,Actinomycetota
...,...,...,...,...,...,...,...,...,...
98,SFLA01,99,VIII,0.005319,0.000000,0.447356,0.005617,146,Bacillota_A_368345
99,1_Mitochondria(F),100,IV,0.005319,0.000000,0.373129,0.000006,27,Pseudomonadota
100,Coprococcus_A_187866,101,II,0.015957,0.000000,0.510584,0.000128,103,Bacillota_A_368345
101,Alitiscatomonas,102,I,0.005319,0.000000,0.418923,0.009476,64,Bacillota_A_368345
102,Eisenbergiella,103,I,0.010638,0.000000,0.473395,0.013610,1675,Bacillota_A_368345

In [10]:
h_re_ab

                    Feature  MeanRelativeAbundance
0               Akkermansia               0.155731
1      Bacteroides_H_857956               0.097207
2             Phocaeicola_A               0.065103
3    Bifidobacterium_388775               0.063673
4               Escherichia               0.059233
..                      ...                    ...
184      Peptostreptococcus               0.000013
185         Peptoniphilus_A               0.000006
186   Sphingomonas_L_486704               0.000003
187              Finegoldia               0.000003
188         Mesorhizobium_I               0.000000

[189 rows x 2 columns]

In [11]:
keys = ["Label"]

h_renamed = h_nodes.rename(columns={
    "Id":"Id_high",
    "cluster":"cluster_high",
    "degree":"degree_high",
    "betweenness":"betweenness_high",
    "closeness":"closeness_high",
    "eigenvector":"eigenvector_high",
    "prevalence":"prevalence_high",
    "abundance":"abundance_high",
})

h_re_ab = h_re_ab.rename(columns={
    "relative_abundance":"high_rel"
})

l_renamed = l_nodes.rename(columns={
    "Id":"Id_low",
    "cluster":"cluster_low",
    "degree":"degree_low",
    "betweenness":"betweenness_low",
    "closeness":"closeness_low",
    "eigenvector":"eigenvector_low",
    "prevalence":"prevalence_low",
    "abundance":"abundance_low",
})

l_re_ab = l_re_ab.rename(columns={
    "relative_abundance":"low_rel"
})

p_renamed = p_nodes.rename(columns={
    "Id":"Id_pibd",
    "cluster":"cluster_pibd",
    "degree":"degree_pibd",
    "betweenness":"betweenness_pibd",
    "closeness":"closeness_pibd",
    "eigenvector":"eigenvector_pibd",
    "prevalence":"prevalence_pibd",
    "abundance":"abundance_pibd",
})

p_re_ab = p_re_ab.rename(columns={
    "relative_abundance":"pibd_rel"
})

In [12]:
merged = h_renamed.merge(l_renamed, on=keys, how="outer")

In [13]:
merged_final = merged.merge(p_renamed, on=keys, how="outer")

In [14]:
merged_final.sort_values('Label', ascending=True)

merged_final

,Label,Id_high,cluster_high,degree_high,betweenness_high,closeness_high,eigenvector_high,abundance_high,phylum_x,Id_low,...,abundance_low,phylum_y,Id_pibd,cluster_pibd,degree_pibd,betweenness_pibd,closeness_pibd,eigenvector_pibd,abundance_pibd,phylum
0,1_Anaerotignaceae(F),77.0,I,0.005319,0.000000,0.517373,0.061840,259.0,Bacillota_A_368345,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_Anaerovoracaceae(F),59.0,II,0.005319,0.000000,0.427255,0.000021,427.0,Bacillota_A_368345,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_Aristaeellaceae(F),75.0,VIII,0.015957,0.155921,0.564901,0.006749,511.0,Bacillota_A_368345,78.0,...,135.0,Bacillota_A_368345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_Bacteria(K),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,V,0.015957,0.000926,0.381952,0.000502,210.0,__
4,1_CAG-138(F),94.0,III,0.005319,0.000000,0.335221,0.000705,90.0,Bacillota_A_368345,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,UBA737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,...,99.0,Bacillota_A_368345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,UMGS1071,81.0,I,0.010638,0.013816,0.547871,0.062512,482.0,Bacillota_A_368345,102.0,...,426.0,Bacillota_A_368345,73.0,I,0.026596,0.191667,0.660107,0.389116,664.0,Bacillota_A_368345
143,Veillonella_A,12.0,I,0.031915,0.042544,0.517076,0.013114,3190.0,Bacillota_C,15.0,...,2453.0,Bacillota_C,16.0,V,0.031915,0.072531,0.605544,0.014662,6580.0,Bacillota_C
144,Ventrisoma,69.0,VIII,0.010638,0.000000,0.485079,0.005777,349.0,Bacillota_A_368345,103.0,...,181.0,Bacillota_A_368345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,Vescimonas,35.0,I,0.058511,0.033772,0.709049,0.444085,3866.0,Bacillota_A_368345,39.0,...,252.0,Bacillota_A_368345,38.0,IV,0.026596,0.076543,0.542490,0.117641,1089.0,Bacillota_A_368345

In [15]:
# merged
merged_final["phylum"] = (
    merged_final["phylum_x"]
    .combine_first(merged_final["phylum_y"])
    .combine_first(merged_final["phylum"])
)

# conflict check
conflict_mask = (
    (merged_final["phylum_x"].notna()) &
    (merged_final["phylum_y"].notna()) &
    (merged_final["phylum_x"] != merged_final["phylum_y"])
)

if conflict_mask.any():
    print("phylum_x vs phylum_y mismatch detected")
    print(merged_final.loc[conflict_mask, ["Id", "phylum_x", "phylum_y"]].head())

# column delete
merged_final = merged_final.drop(columns=["phylum_x", "phylum_y"], errors="ignore")

In [16]:
merged_final = merged_final.sort_values(by = ['Id_high'], ascending=True).copy()

In [17]:
merged_final

,Label,Id_high,cluster_high,degree_high,betweenness_high,closeness_high,eigenvector_high,abundance_high,Id_low,cluster_low,...,eigenvector_low,abundance_low,Id_pibd,cluster_pibd,degree_pibd,betweenness_pibd,closeness_pibd,eigenvector_pibd,abundance_pibd,phylum
135,Sutterella,1.0,I,0.010638,0.000000,0.526809,0.105146,70.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pseudomonadota
79,Gemmiger_A_73129,2.0,II,0.037234,0.167105,0.620746,0.000616,16191.0,2.0,III,...,0.364135,10857.0,3.0,I,0.026596,0.000309,0.558780,0.415493,10823.0,Bacillota_A_368345
108,Methanobrevibacter_A,3.0,III,0.015957,0.001316,0.456678,0.019196,2785.0,3.0,IV,...,0.001567,796.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Methanobacteriota_A_1229
35,Bacteroides_H_857956,4.0,I,0.122340,0.096491,0.872304,0.912477,30354.0,4.0,I,...,0.039692,9672.0,4.0,I,0.037234,0.075926,0.628978,0.676889,27198.0,Bacteroidota
38,Bifidobacterium_388775,5.0,II,0.095745,0.021272,0.756596,0.000724,20069.0,5.0,II,...,0.456533,29916.0,6.0,III,0.015957,0.000309,0.530726,0.029955,21583.0,Actinomycetota
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Pseudomonas_E_647464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,II,...,0.080163,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pseudomonadota
130,Schaedlerella,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,II,...,0.246599,135.0,61.0,II,0.005319,0.000000,0.454584,0.021077,546.0,Bacillota_A_368345
133,Sphingomonas_L_486704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,71.0,XI,0.000000,0.000000,0.000000,0.000000,99.0,Pseudomonadota
140,UBA644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,I,...,0.000588,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacillota_A_368345
141,UBA737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,0,...,0.000000,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacillota_A_368345

In [18]:
## Export to one of file

h_edges['group'] = "high_edge"

l_edges['group'] = "low_edge"

p_edges['group'] = "pibd_edge"

con_edges = pd.concat([h_edges, l_edges, p_edges])

con_edges

,Source,Target,Type,Weight,Sign,asso,group
0,Sutterella,Bacteroides_H_857956,Undirected,0.412594,Positive,0.309908,high_edge
1,Sutterella,Odoribacter_865974,Undirected,0.430016,Positive,0.350237,high_edge
2,Sutterella,Lentihominibacter,Undirected,0.193513,Negative,-0.300843,high_edge
3,Gemmiger_A_73129,Collinsella,Undirected,0.508441,Positive,0.516739,high_edge
4,Gemmiger_A_73129,Bariatricus,Undirected,0.460420,Positive,0.417708,high_edge
...,...,...,...,...,...,...,...
228,Finegoldia,Fusobacterium_C,Undirected,0.438994,Positive,0.370544,pibd_edge
229,Faecalimonas,Ruminococcus_B,Undirected,0.460586,Positive,0.418065,pibd_edge
230,Fusobacterium_C,Haemophilus_D_735815,Undirected,0.468787,Positive,0.435625,pibd_edge
231,Eisenbergiella,Parasutterella_564865,Undirected,0.409130,Positive,0.301745,pibd_edge
232,Haemophilus_D_735815,Hungatella_A_128155,Undirected,0.411021,Positive,0.306209,pibd_edge

In [19]:
merged_final

,Label,Id_high,cluster_high,degree_high,betweenness_high,closeness_high,eigenvector_high,abundance_high,Id_low,cluster_low,...,eigenvector_low,abundance_low,Id_pibd,cluster_pibd,degree_pibd,betweenness_pibd,closeness_pibd,eigenvector_pibd,abundance_pibd,phylum
135,Sutterella,1.0,I,0.010638,0.000000,0.526809,0.105146,70.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pseudomonadota
79,Gemmiger_A_73129,2.0,II,0.037234,0.167105,0.620746,0.000616,16191.0,2.0,III,...,0.364135,10857.0,3.0,I,0.026596,0.000309,0.558780,0.415493,10823.0,Bacillota_A_368345
108,Methanobrevibacter_A,3.0,III,0.015957,0.001316,0.456678,0.019196,2785.0,3.0,IV,...,0.001567,796.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Methanobacteriota_A_1229
35,Bacteroides_H_857956,4.0,I,0.122340,0.096491,0.872304,0.912477,30354.0,4.0,I,...,0.039692,9672.0,4.0,I,0.037234,0.075926,0.628978,0.676889,27198.0,Bacteroidota
38,Bifidobacterium_388775,5.0,II,0.095745,0.021272,0.756596,0.000724,20069.0,5.0,II,...,0.456533,29916.0,6.0,III,0.015957,0.000309,0.530726,0.029955,21583.0,Actinomycetota
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Pseudomonas_E_647464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,II,...,0.080163,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pseudomonadota
130,Schaedlerella,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,II,...,0.246599,135.0,61.0,II,0.005319,0.000000,0.454584,0.021077,546.0,Bacillota_A_368345
133,Sphingomonas_L_486704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,71.0,XI,0.000000,0.000000,0.000000,0.000000,99.0,Pseudomonadota
140,UBA644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,I,...,0.000588,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacillota_A_368345
141,UBA737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.0,0,...,0.000000,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bacillota_A_368345

In [ ]:
merged_final.to_csv("data/3_results/5_network_analysis/5_3_network_align/rome_merged_nodes.csv", sep=',')
con_edges.to_csv("data/3_results/5_network_analysis/5_3_network_align/merged_edges.csv", sep=',')